/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rodrigo' at '17/09/16 17:21' with Gradle 2.14
 *
 * @author Rodrigo, @date 17/09/16 17:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
